### ISSUE TITLE
Make turns bleed speed

### ISSUE THREAD

**Issue by PeterNerlich** [TheQuantumBlaze/Fzero#3]
When turning, the vehicle should bleed speed. The real world explanation would be additional forces from the tires diverting the vehicle from the straight path along its momentum vector, while the energy fed into the system (by the engine) stays constant and aligned with the vehicle itself.

This creates an additional incentive for the player to reduce steering amount and take higher risks of crashing because it more directly translates to lost time.

**Comment by TheQuantumBlaze** [comment]
10% bleed per second?

**Comment by TheQuantumBlaze** [comment]
adjusted to 20% per second
